name: Build and Push Docker Image(s) to Container Registry

on:
  push:
    branches: ['main']
    paths: ['.dockerignore', '**/Dockerfile']

env:
  REGISTRY: ghcr.io

jobs:
  get_changed_docker_images:
    name: Get changed Docker images
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAMES: ${{ steps.get_image_names.outputs.IMAGE_NAMES }}
    steps:
      - name: Check out repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - name: Get changed files
        run: |
          changed_files="$(git diff --name-only ${{ github.event.before }} HEAD | xargs)"
          echo "CHANGED_FILES=$changed_files" >> $GITHUB_ENV
      - name: Get changed docker image names
        id: get_image_names
        shell: python
        run: |
          import json
          import os

          files = os.getenv("CHANGED_FILES").split(" ")
          images = []

          for file in files:
            parts = file.split("/")

            if parts[-1] == "Dockerfile":
              images.append(parts[-2])

            with open(os.getenv("GITHUB_OUTPUT"), "a") as f:
              print(f"IMAGE_NAMES={json.dumps(images)}", file=f)
  build_push:
    name: Build and push ${{ matrix.image }} to Container Registry
    runs-on: ubuntu-latest
    needs: get_changed_docker_images
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        image: ${{ fromJSON(needs.get_changed_docker_images.outputs.IMAGE_NAMES) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Login to Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set docker image metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image }}
          tags: |
            type=sha,prefix=,format=long
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          file: ./${{ matrix.image }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
